CREATE TABLE IF NOT EXISTS NUsers (id INTEGER PRIMARY KEY, name TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS NLists (id INTEGER PRIMARY KEY, name TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS NPlatforms (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS NGenres (id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE);

CREATE TABLE IF NOT EXISTS NGames (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    released TEXT NOT NULL,
    image_id TEXT
);

CREATE TABLE IF NOT EXISTS NGenreGames (
    id INTEGER PRIMARY KEY,
    game_id INTEGER,
    genre_id INTEGER
);

CREATE TABLE IF NOT EXISTS NPlatformGames (
    id INTEGER PRIMARY KEY,
    game_id INTEGER,
    platform_id INTEGER
);

-- THE FOLLOWING TABLE IS THE ONE FOR STORING THE USER'S LISTS
CREATE TABLE IF NOT EXISTS NListGames (
    id INTEGER PRIMARY KEY, 
    game_id INTEGER, 
    list_id INTEGER,
    user_id INTEGER
);