DELETE FROM NUsers;
DELETE FROM NListGames;
DELETE FROM NPlatformGames;
DELETE FROM NGenreGames;
DELETE FROM NLists;
DELETE FROM NGames;
DELETE FROM NGenres;
DELETE FROM NPlatforms;

DROP TABLE IF EXISTS NUsers;
DROP TABLE IF EXISTS NListGames;
DROP TABLE IF EXISTS NPlatformGames;
DROP TABLE IF EXISTS NGenreGames;
DROP TABLE IF EXISTS NLists;
DROP TABLE IF EXISTS NGames;
DROP TABLE IF EXISTS NGenres;
DROP TABLE IF EXISTS NPlatforms;