INSERT OR REPLACE INTO NGenres (id, name) VALUES (1, "Shooter");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (2, "Simulator");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (3, "Adventure");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (4, "Role-playing (RPG)");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (5, "Strategy");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (6, "Turn-based strategy (TBS)");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (7, "Tactical");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (8, "Real Time Strategy (RTS)");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (9, "Point-and-click");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (10, "Puzzle");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (11, "Fighting");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (12, "Racing");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (13, "Hack and slash/Beat 'em up");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (14, "Platform");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (15, "Arcade");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (16, "Sport");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (17, "Indie");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (18, "MOBA");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (19, "Music");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (20, "Quiz/Trivia");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (21, "Card & Board Game");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (22, "Visual Novel");
INSERT OR REPLACE INTO NGenres (id, name) VALUES (23, "Pinball");