INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (1, "PC (Microsoft Windows)");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (2, "Xbox");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (3, "PlayStation 3");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (4, "Xbox 360");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (5, "Mac");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (6, "PlayStation 4");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (7, "Xbox One");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (8, "Linux");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (9, "iOS");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (10, "DOS");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (11, "Nintendo DS");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (12, "Amiga");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (13, "Android");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (14, "PlayStation 2");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (15, "PlayStation");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (16, "Atari ST/STE");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (17, "Apple II");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (18, "Apple IIGS");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (19, "Wii");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (20, "FM Towns");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (21, "PC-98");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (22, "Sega CD");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (23, "Wii U");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (24, "Nintendo Switch");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (25, "Nintendo GameCube");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (26, "Game Boy Advance");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (27, "Xbox Series X|S");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (28, "Sega Mega Drive/Genesis");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (29, "Acorn Archimedes");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (30, "Sega Saturn");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (31, "3DO Interactive Multiplayer");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (32, "PlayStation Portable");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (33, "Commodore C64/128/MAX");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (34, "PlayStation Vita");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (35, "Dreamcast");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (36, "Nintendo 64");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (37, "Game Boy Color");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (38, "Nintendo Entertainment System");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (39, "Amstrad CPC");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (40, "ZX Spectrum");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (41, "MSX");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (42, "Atari 7800");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (43, "Atari 8-bit");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (44, "Atari 5200");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (45, "Game Boy");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (46, "Sega Game Gear");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (47, "Sega Master System/Mark III");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (48, "Turbografx-16/PC Engine CD");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (49, "Arcade");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (50, "Super Famicom");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (51, "BBC Microcomputer System");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (52, "TRS-80 Color Computer");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (53, "Nintendo 3DS");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (54, "Atari Jaguar");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (55, "Windows Phone");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (56, "Super Nintendo Entertainment System");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (57, "TurboGrafx-16/PC Engine");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (58, "Sharp X68000");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (59, "Handheld Electronic LCD");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (60, "Amiga CD32");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (61, "Web browser");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (62, "Zeebo");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (63, "Tapwave Zodiac");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (64, "Philips CD-i");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (65, "Nintendo PlayStation");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (66, "Legacy Mobile Device");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (67, "Family Computer Disk System");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (68, "Family Computer");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (69, "Google Stadia");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (70, "MSX2");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (71, "PlayStation 5");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (72, "Ouya");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (73, "WonderSwan");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (74, "Sega 32X");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (75, "N-Gage");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (76, "OnLive Game System");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (77, "Satellaview");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (78, "Atari 2600");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (79, "ColecoVision");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (80, "SG-1000");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (81, "New Nintendo 3DS");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (82, "Nintendo DSi");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (83, "Virtual Boy");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (84, "WonderSwan Color");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (85, "Commodore 16");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (86, "Commodore Plus/4");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (87, "TRS-80");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (88, "Amstrad PCW");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (89, "Tatung Einstein");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (90, "Texas Instruments TI-99");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (91, "Intellivision");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (92, "Commodore VIC-20");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (93, "Odyssey 2 / Videopac G7000");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (94, "Acorn Electron");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (95, "Neo Geo MVS");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (96, "Neo Geo AES");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (97, "Neo Geo CD");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (98, "Vectrex");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (99, "Sharp X1");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (100, "Nintendo 64DD");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (101, "PC-8801");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (102, "FM-7");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (103, "NEC PC-6000 Series");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (104, "BlackBerry OS");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (105, "Sharp MZ-2200");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (106, "Palm OS");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (107, "AY-3-8606");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (108, "Thomson MO5");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (109, "Commodore PET");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (110, "PDP-11");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (111, "Windows Mixed Reality");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (112, "SteamVR");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (113, "Oculus Rift");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (114, "Atari Lynx");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (115, "Call-A-Computer time-shared mainframe computer system");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (116, "Dragon 32/64");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (117, "DVD Player");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (118, "Mega Duck/Cougar Boy");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (119, "Oculus VR");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (120, "Daydream");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (121, "PC-FX");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (122, "PC Engine SuperGrafx");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (123, "Commodore CDTV");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (124, "Windows Mobile");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (125, "PlayStation VR");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (126, "PlayStation VR2");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (127, "Amazon Fire TV");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (128, "VC 4000");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (129, "1292 Advanced Programmable Video System");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (130, "Donner Model 30");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (131, "PC-50X Family");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (132, "AY-3-8710");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (133, "Imlac PDS-1");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (134, "Odyssey");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (135, "Bally Astrocade");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (136, "PDP-8");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (137, "PDP-10");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (138, "DEC GT40");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (139, "Gamate");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (140, "Meta Quest 2");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (141, "Blu-ray Player");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (142, "Plug & Play");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (143, "Neo Geo Pocket");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (144, "Oculus Quest");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (145, "PDP-1");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (146, "PDP-7");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (147, "Analogue electronics");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (148, "Ferranti Nimrod Computer");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (149, "EDSAC");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (150, "HP 2100");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (151, "CDC Cyber 70");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (152, "HP 3000");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (153, "SDS Sigma 7");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (154, "Microcomputer");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (155, "PLATO");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (156, "Virtual Console (Nintendo)");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (157, "Gear VR");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (158, "Sinclair ZX81");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (159, "AY-3-8760");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (160, "Fairchild Channel F");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (161, "AY-3-8607");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (162, "Intellivision Amico");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (163, "Hyper Neo Geo 64");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (164, "Neo Geo Pocket Color");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (165, "PocketStation");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (166, "V.Smile");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (167, "Oculus Go");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (168, "Pokémon mini");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (169, "OOParts");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (170, "AY-3-8603");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (171, "Leapster Explorer/LeadPad Explorer");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (172, "Leapster");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (173, "Epoch Cassette Vision");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (174, "Sega Pico");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (175, "Game.com");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (176, "Nuon");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (177, "Arduboy");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (178, "Legacy Computer");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (179, "Watara/QuickShot Supervision");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (180, "Epoch Super Cassette Vision");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (181, "Playdia");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (182, "Casio Loopy");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (183, "Game & Watch");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (184, "Microvision");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (185, "AY-3-8500");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (186, "AY-3-8610");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (187, "AY-3-8605");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (188, "Atari Jaguar CD");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (189, "HyperScan");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (190, "LeapTV");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (191, "DUPLICATE Stadia");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (192, "Exidy Sorcerer");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (193, "Sol-20");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (194, "Evercade");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (195, "Playdate");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (196, "AirConsole");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (197, "Sinclair QL");
INSERT OR REPLACE INTO NPlatforms (id, name) VALUES (198, "Visual Memory Unit / Visual Memory System");
